---
- name: Install and Start the service
  hosts: all

  tasks:
  - name: Installing nginx
    apt:
      name: nginx
      state: latest
  - name: Starting the nginx service
    service:
      name: nginx
      state: started
      enabled: true     
